version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      build:
        docker:
          - image: cimg/node:15.5.0
        steps:
          - run:
              name: Starts firebase emulators
              command: |
                firebase emulators:start
          - run:
              name: Starts tests
              command: |
                npm test
              
