version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    docker:
      - image: cimg/node:12.20.0
        auth:
          username: burhancoulibaly
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Workaround for running apt behind the scene
          command: sudo killall -9 apt-get || true
      - run:
          name: Switch to US mirror for faster performances
          command: sudo sed -i 's/\/\/archive.ubuntu.com/\/\/us.archive.ubuntu.com/g' /etc/apt/sources.list
      - run:
          name: Add openjdk-r PPA
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo apt-get update
      - run:
          name: Generate cache version
          command: |
            apt-cache policy openjdk-<< parameters.version >>-jdk | grep 'Candidate:' | cut -d' ' -f4 > .openjdk_version
            cat .openjdk_version
      - restore_cache:
          keys:
          - apt-cache-{{ checksum ".openjdk_version" }}-v<< parameters.cache_version >>
      - run:
          name: Create temp directory if restore cache didn't
          command: mkdir -p /tmp/archives
      - run:
          name: Restore apt cache
          command: sudo rsync -av /tmp/archives/ /var/cache/apt/archives/
      - run:
          name: Install openjdk-<< parameters.version >>-jdk
          command: |
            sudo apt-get install -y openjdk-<< parameters.version >>-jdk
            sudo update-java-alternatives --set java-1.<< parameters.version >>.0-openjdk-amd64
      - node/install-packages
      - run:
          name: "Install firebase tools"
          command: |
            curl -sL https://firebase.tools | bash
      - run:
          name: "Start firebase emulators and test"
          command: |
            firebase emulators:exec --only firestore "npm test"

workflows:
  Chat_From_Home_Test:
    jobs:
      - test
