version: 2.1
orbs:
  node: circleci/node@3.0.0
  openjdk-install: cloudesire/openjdk-install@1.2.3
  java11: drift/java11@0.1.1

jobs:
  test:
    docker:
      - image: cimg/node:10.21.0
        auth:
          username: burhancoulibaly
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - java11/install-java11-and-maven36
      - node/install-packages
      - run:
          name: "Install firebase tools"
          command: |
            sudo npm install -g firebase-tools
      - run:
          name: "run build"
          command: |
            npm run build
      - run:
          name: "Start firebase emulators and test"
          command: |
            firebase emulators:exec --project chat-from-home --only firestore "npm test"

workflows:
  Chat_From_Home_Test:
    jobs:
      - test
