jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: firebase emulators:start

version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  "Test":
    jobs:
      - node/test

              
