version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    docker:
      - image: cimg/node:12.20.0
        auth:
          username: burhancoulibaly
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "add openjdk repo"
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo apt-get update
      - run:
          name: "add openjdk repo"
          command: |
            sudo apt-get install default-jdk
      - run:
          name: "Install firebase tools"
          command: |
            curl -sL https://firebase.tools | bash
      - run:
          name: "Start firebase emulators and test"
          command: |
            firebase emulators:exec --only firestore "npm test"

workflows:
  Chat_From_Home_Test:
    jobs:
      - test
